class_name DeckLibrary
## Loads decks from authorable .tres (editor-first). Content is generated by
## tools/gen/gen_content.gd and can then be hand-edited in the Godot inspector.

const STARTER_PATH := "res://data/decks/starter.tres"
const REWARD_POOL_PATH := "res://data/decks/reward_pool.tres"

static func starter_deck() -> Array:
	return _cards(STARTER_PATH)

static func reward_pool() -> Array:
	return _cards(REWARD_POOL_PATH)

static func _cards(path: String) -> Array:
	var deck: DeckData = load(path)
	if deck == null:
		push_error("DeckLibrary: deck missing at " + path)
		return []
	var out: Array = []
	for c in deck.cards:
		out.append(c)
	return out
