class_name DeckLibrary
## Loads decks from authorable .tres (editor-first). Content is generated by
## tools/gen/gen_content.gd and can then be hand-edited in the Godot inspector.
## Meta inversion: the reward pool ships WHOLE -- nothing is meta-locked anymore.

const REWARD_POOL_PATH := "res://data/decks/reward_pool.tres"

## Selectable starter decks (Profile.available_decks gates which ids are offered).
const STARTERS := {
	"classic": "res://data/decks/starter.tres",
	"reaper": "res://data/decks/starter_reaper.tres",
	"gardener": "res://data/decks/starter_gardener.tres",
	"oracle": "res://data/decks/starter_oracle.tres",
}

static func deck_name_key(id: String) -> String:
	return "DECK_" + id.to_upper()

static func deck_desc_key(id: String) -> String:
	return "DECK_" + id.to_upper() + "_DESC"

static func starter_deck() -> Array:
	var prof := _profile()
	var id := "classic"
	if prof != null and prof.available_decks().has(prof.selected_deck):
		id = prof.selected_deck
	return starter_deck_by_id(id)

## Pure Reading (shared fates): the classic starter with NO profile editions -- byte-identical
## for every player, so a shared seed is provably the same run.
static func starter_deck_pure() -> Array:
	return _cards(STARTERS["classic"])

static func starter_deck_by_id(id: String) -> Array:
	var cards := _cards(STARTERS.get(id, STARTERS["classic"]))
	# Permanent meta upgrades: the profile's starter editions apply to every new run.
	var prof := _profile()
	if prof != null:
		for i in cards.size():
			var ed: int = prof.starter_editions.get("%s:%d" % [id, i], CardData.Edition.NONE)
			if ed != CardData.Edition.NONE:
				cards[i].edition = ed as CardData.Edition
	return cards

static func reward_pool() -> Array:
	return _cards(REWARD_POOL_PATH)

static func full_reward_pool() -> Array:
	return _cards(REWARD_POOL_PATH)

static func _profile() -> Node:
	var ml := Engine.get_main_loop()
	if ml is SceneTree:
		return (ml as SceneTree).root.get_node_or_null("Profile")
	return null

static func _cards(path: String) -> Array:
	var deck: DeckData = load(path)
	if deck == null:
		push_error("DeckLibrary: deck missing at " + path)
		return []
	var out: Array = []
	for c in deck.cards:
		out.append(c.duplicate())  # run-local copies so editions never mutate the shared .tres
	return out
